version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: bioconsumo

    working_directory: ~/bioconsumo

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt install -y default-mysql-client
      - run: sudo composer self-update

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Setup Laravel stuff
          command: |
            cp .env.testing .env
            php artisan key:generate
            php artisan config:cache
            php artisan migrate:fresh --seed --force
      - run: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.2-node
    working_directory: ~/bioconsumo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:5a:d7:aa:12:8e:52:f1:19:a5:b9:95:29:1e:55:45"
      - run: ssh-keyscan ec2-18-224-22-153.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - checkout
      - run:
          name: Build production assets
          command: |
            yarn
            yarn production
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            sudo mv deployer.phar /usr/local/bin/dep
            sudo chmod +x /usr/local/bin/dep
      - run:
          name: Deploy
          command: |
            dep deploy
workflows:
  version: 2
  notify_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
